language: cpp

matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx

dist: xenial

addons:
  homebrew:
    update: true
    packages:
    - eigen
    - qt
  apt:
    packages:
    - libeigen3-dev
    - libqt5opengl5-dev
    - qt5-default

script:
  - cmake . -DENHANCER_BUILD_QT_TESTS=ON -DENHANCER_USE_QT_FEATURES=ON
  - make
  - ctest
